# Generated by Django 3.1.7 on 2021-06-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pics',
            field=models.ManyToManyField(blank=True, related_name='profile_pictures', to='Image.File'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='cover',
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ManyToManyField(blank=True, related_name='covers', to='Image.File'),
        ),
    ]
