# Generated by Django 3.1.7 on 2021-06-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210628_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cover',
            new_name='cover_pics',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
